AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-memo-demo

  Sample SAM Template for sam-memo-demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  MemoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      #app.py is under hello_world
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      VpcConfig:
        SubnetIds:
          - "subnet-0439b9ab02afa1e4d"
          - "subnet-08ecfdd4622a9c2ab"
          - "subnet-00794b3ddb1577336"
        SecurityGroupIds:
          - "sg-0670acaa1ebc59a13"
      Architectures:
      - x86_64
      Events:
        MemoApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /memo
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MemoApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/memo/"
  MemoFunction:
    Description: Memo Lambda Function ARN
    Value: !GetAtt MemoFunction.Arn
  MemoFunctionIamRole:
    Description: Implicit IAM Role created for Memo function
    Value: !GetAtt MemoFunctionRole.Arn
